name: Build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
      - 'setup.iss'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
      - 'setup.iss'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of caesium-image-compressor to build: v2.8.3'
        default: v2.8.3
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of caesium-image-compressor to build: v2.8.3'
        default: v2.8.3
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v4
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build-${{ runner.os }}/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: '6.8.2'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qtimageformats'
          cache: true

      - name: Install linuxdeployqt and squashfuse
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfuse
          wget "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-${{ runner.os }} -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build-${{ runner.os }} --config Release --target caesium_image_compressor

      - name: Create AppImage
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu  # This is crucial for squashfuse
        run: |
          cd ${{github.workspace}}/build-${{ runner.os }}
          ../linuxdeployqt-continuous-x86_64.AppImage --appimage-extract-and-run caesium-image-compressor -appdir -unsupported-allow-new-glibc
          mv caesium-image-compressor*.AppImage ../

      - name: Upload AppImage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caesium-image-compressor-${{ inputs.version }}-ubuntu.AppImage
          path: ${{github.workspace}}/build-${{ runner.os }}/caesium-image-compressor*.AppImage

      - name: Upload AppImage to GitHub Release
        id: upload-release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file_glob: true
          file: ${{github.workspace}}/build-${{ runner.os }}/caesium-image-compressor*.AppImage
          release_name: caesium_image_compressor-${{ inputs.version }}
          tag: ${{ inputs.version }}
          make_latest: true
          prerelease: false
          overwrite: true
